var EMOJIS = [
  { emoji: "😀", name: "grinning face smile happy" },
  { emoji: "😁", name: "grin happy" },
  { emoji: "😂", name: "laugh joy tears funny" },
  { emoji: "🤣", name: "rofl laugh funny" },
  { emoji: "😊", name: "smile blush happy" },
  { emoji: "😍", name: "love heart eyes" },
  { emoji: "😘", name: "kiss love" },
  { emoji: "😎", name: "cool sunglasses" },
  { emoji: "🤔", name: "thinking hmm" },
  { emoji: "😢", name: "sad cry" },
  { emoji: "😭", name: "crying tears" },
  { emoji: "🔥", name: "fire hot lit" },
  { emoji: "🚀", name: "rocket launch space" },
  { emoji: "💡", name: "idea bulb" },
  { emoji: "✅", name: "check ok done" },
  { emoji: "❌", name: "cross error no" },
  { emoji: "👍", name: "thumb up like yes" },
  { emoji: "👎", name: "thumb down no" },
  { emoji: "👏", name: "clap bravo" },
  { emoji: "🙏", name: "pray thanks please" },
  { emoji: "❤️", name: "heart love" }
];